    <div class="container">
        <div class="login valign-wrapper row">
            <div class="col s12 m6 l6 offset-m3 offset-l3">
                <form class="hoverable" action="/mvc/ValidaLogin" method="POST">
                    <div class="input-field">
                        <i class="material-icons prefix fa fa-user"></i>
                        <input type="text" class="validate" id="usuario" name="usuario" placeholder="Usuario">
                        <label for="usuario">Usuario</label>
                    </div>
                    <div class="input-field">
                        <i class="material-icons prefix fa fa-unlock-alt"></i>
                        <input type="password" class="validate" id="senha" name="senha" placeholder="Senha">
                        <label for="senha">Senha</label>
                    </div>
                    <button class="btn">Logar</button>
                </form>
            </div>
        </div>
    </div>