    <div class="row">
        <div class="col s12 m6 l6 offset-m3 offset-l3">
            <form action="../../Assets/js/login.js" method="POST">
                <label for="usuario">Usuario: </label>
                <input type="text" id="usuario" name="usuario" placeholder="Usuario">

                <label for="senha">Senha: </label>
                <input type="password" id="senha" name="senha" placeholder="Senha">

                <button>Logar</button>
            </form>
        </div>
    </div>